### ISSUE TITLE
Missing "addAutoImport" export in nuxt/kit

### ISSUE THREAD

**Issue by pkej** [Diizzayy/nuxt-gql#4]
After following the readme I weren't able to start nuxt:

```sh
ERROR  Cannot start nuxt:  The requested module '@nuxt/kit' does not provide an export named 'addAutoImport'                                                              12:58:23

  import { useLogger, defineNuxtModule, createResolver, addTemplate, addAutoImport, resolveFiles } from '@nuxt/kit';
```

My nuxt-installation is based on this template:

[antfu/vitesse-nuxt3](https://github.com/antfu/vitesse-nuxt3)

**Comment by Diizzayy** [comment]
@pkej I was unable to reproduce this issue using the same template.

I created [this repo](https://github.com/Diizzayy/vitesse-nuxt3) with `vitesse-nuxt3` so you can have a look.
